spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/ms-category
    username: ms-category
    password: ms-category
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
