spring:
  datasource:
    url: jdbc:postgresql://localhost:5443/ms-relations
    username: ms-relations
    password: ms-relations
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5671
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2s
