spring:
  application:
    name: ms-relations
  profiles:
    active: dev

server:
  port: 0
  servlet:
    contextPath: /relations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

amqp:
  exchange:
    relations:
      product-category:
        name: product-category
