spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/ms-product
    username: ms-product
    password: ms-product
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
